# LOCAL
GET http://localhost:8080/contacts

GET http://localhost:8080/contacts/6a9aa9a1f438184bee4bcc33



# PRODUCTION
GET https://contacts-api-3zsh.onrender.com/contacts/

GET https://contacts-api-3zsh.onrender.com/contacts/6963a253da25ece8ced8f979

